language: node_js
node_js:
- '8'
script:
- ionic build
install:
- yarn global add firebase-tools cordova ionic @angular/cli
- yarn
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: never
    on_success: never
env:
  global:
    secure: CCADxvjXdEmaCoKwBMdhOLfqdWYW4a+jeTVk1gFRMDeh/vjdpmSnQXJGialRqO+3mqoE6AAvm7WnjuY/+oMqT6vz2R8MQWoods1WkcFwbFF23Ql86PemYwu+mNTmXuWMzZDr6bu6WzJMLA7hYrO1pgWAKtX4wZD/lHOVuVvcrPB8c1cD83Hmuyx+Kf1JDPnI7qgdnd9ikjxLliJNjoSAcyYmtcJ35wrW1DtPiQeXW/F9IkQTUohNnH1YkPoXu8roHdSgUEqaXEgyVcBFHUBr2W03RCrVg7Ax2DnyyBU+t7JSwBBx/FnOEvIxMpnRXaNctwEfRqGiOs1P7LL+yonQpUj3D7WMTs08O+0DnkfmP9Nh/4quIES0tA/07beR7OpqhBwew8orTUYOWaNbcgsCKc1V/sqVZ3BQJL8W15rYNeA3QgvFfqF1xNZy5s9Sj2Eq1IZZJJZm2xSNMBo37xUQzc58oxCOF0EAVxxuik+Lhuz4xjbqAXnKTEBwhTt23WkKHE8Abl7hfg3NmasqViioUfKB/HcLuENQqhszpQ8dwEWFObB+GodH384MySXMd/p9Fqnwvx/PyxQljD2MMV+VFZWsZKA6gMCcInUy5nUEJ42PaPddF1L5HljJoZD7eWC1kW7ss6NuOekfFcyq7EXGsH85yQna+nxXXadOlcRf/8M=
